language: python
python:
  - "3.7"
  - "3.8"
before_install:
- sudo apt-get update
- sudo apt-get install -y pandoc
- pip install poetry
install:
- poetry install
script:
- poetry run flake8
- poetry run pytest
